### ISSUE TITLE
Add "Jump to Slice"

### ISSUE THREAD

**Issue by amyleerobinson** [r03ert0/BrainBox#2]

**Comment by r03ert0** [comment]
not yet jump to slice, but now brainbox remembers the view plane and slice of the last place you were. You can also have a direct URL to a brain instead of having to type it on the input field. For example, click here:
http://siphonophore.org/brainbox/index.html?url=https://zenodo.org/record/44855/files/MRI-n4.nii.gz

pick any plane (sag, axi or cor) and go to some slice. Then reload: brainbox should take you to where you left.

**Comment by r03ert0** [comment]
now brainbox keeps track of all brains visited and the last slices edited. I added a list of "Recently visited" brains.

**Comment by amyleerobinson** [comment]
Sweet!

On Wed, Mar 9, 2016 at 3:52 PM, Roberto Toro <notifications@github.com>
wrote:

> now brainbox keeps track of all brains visited and the last slices edited.
> I added a list of "Recently visited" brains.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/r03ert0/BrainBox/issues/2#issuecomment-194502489>.
>



-- 
Director, EyeWire <http://eyewire.org/> | Founder, TEDx Music Project
<http://tedxmusicproject.com/>
@amyleerobinson <https://twitter.com/amyleerobinson>

**Comment by r03ert0** [comment]
Implemented as URL parametres. Now you can use URLs like this:

http://localhost/brainbox/index.html?url=http://braincatalogue.org/data/Demidoff%27s_dwarf_galago/MRI.nii.gz&view=axi&slice=30&fullscreen=true

to set the view to axial (possibilities are sag, cor and axi) and move to slice 30.
